name: citeams
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.11
  - numpy==1.23.5
  - pydantic==1.10.7
  - scipy==1.10.1
  - ipykernel #need for installing conda as a jupyter kernel
  - pip==23.0.1
  - pip:
    - certif-pyspec==1.5.3
